In [ ]:
# EXPERIMENT 14 DATA BINNING AND DATA FORMATTING USING PYTHON
# maitreyee upadhyay 25070123071

In [2]:
import pandas as pd
import numpy as np

data = {
    'product': ['laptop', 'mobile', 'tablet', 'headphones', 'smartwatch','camera'],
    'price': [55000,20000,30000,2000,8000,45000],
    'unit': ['pcs', 'pcs', 'pcs', 'pcs', 'pcs', 'pcs']
}
df = pd.DataFrame(data)
print(df)

      product  price unit
0      laptop  55000  pcs
1      mobile  20000  pcs
2      tablet  30000  pcs
3  headphones   2000  pcs
4  smartwatch   8000  pcs
5      camera  45000  pcs

In [3]:
# data binning
bins1 = [0,10000,30000,60000]
labels1 = ['low','medium','high']

df['price_category'] = pd.cut(df['price'],bins=bins1,labels=labels1)
print(df)

      product  price unit price_category
0      laptop  55000  pcs           high
1      mobile  20000  pcs         medium
2      tablet  30000  pcs         medium
3  headphones   2000  pcs            low
4  smartwatch   8000  pcs            low
5      camera  45000  pcs           high

In [5]:
# binning units sold
bins2 = [0,30,60,100]
labels2 = ['low sales','medium sales','high sales']

# Add a 'units_sold' column to the DataFrame to resolve the KeyError
df['units_sold'] = [15, 40, 25, 5, 10, 50] # Example data for units sold

df['sales_category'] = pd.cut(df['units_sold'], bins=bins2 , labels=labels2)
print(df)

      product  price unit price_category  units_sold sales_category
0      laptop  55000  pcs           high          15      low sales
1      mobile  20000  pcs         medium          40   medium sales
2      tablet  30000  pcs         medium          25      low sales
3  headphones   2000  pcs            low           5      low sales
4  smartwatch   8000  pcs            low          10      low sales
5      camera  45000  pcs           high          50   medium sales

In [8]:
# data formatting
# convert data type
print(df.dtypes)
df['units_sold'] = df['units_sold'].astype(float)
print(df.dtypes)
df

product             object
price                int64
unit                object
price_category    category
units_sold         float64
sales_category    category
dtype: object
product             object
price                int64
unit                object
price_category    category
units_sold         float64
sales_category    category
dtype: object

      product  price unit price_category  units_sold sales_category
0      laptop  55000  pcs           high        15.0      low sales
1      mobile  20000  pcs         medium        40.0   medium sales
2      tablet  30000  pcs         medium        25.0      low sales
3  headphones   2000  pcs            low         5.0      low sales
4  smartwatch   8000  pcs            low        10.0      low sales
5      camera  45000  pcs           high        50.0   medium sales

In [10]:
# covert text to uppercase
df['product'].str.upper()
df

      product  price unit price_category  units_sold sales_category
0      laptop  55000  pcs           high        15.0      low sales
1      mobile  20000  pcs         medium        40.0   medium sales
2      tablet  30000  pcs         medium        25.0      low sales
3  headphones   2000  pcs            low         5.0      low sales
4  smartwatch   8000  pcs            low        10.0      low sales
5      camera  45000  pcs           high        50.0   medium sales

In [11]:
# rounding values
df['price']= df['price'].round(2)
print(df)

      product  price unit price_category  units_sold sales_category
0      laptop  55000  pcs           high        15.0      low sales
1      mobile  20000  pcs         medium        40.0   medium sales
2      tablet  30000  pcs         medium        25.0      low sales
3  headphones   2000  pcs            low         5.0      low sales
4  smartwatch   8000  pcs            low        10.0      low sales
5      camera  45000  pcs           high        50.0   medium sales

In [16]:
# additional operations
# sort data
sorted_df = df.sort_values(by='price', inplace=True, ascending=False)
df

      product  price unit price_category  units_sold sales_category
0      laptop  55000  pcs           high        15.0      low sales
5      camera  45000  pcs           high        50.0   medium sales
2      tablet  30000  pcs         medium        25.0      low sales
1      mobile  20000  pcs         medium        40.0   medium sales
4  smartwatch   8000  pcs            low        10.0      low sales
3  headphones   2000  pcs            low         5.0      low sales

In [17]:
# display unique values
print(df['price_category'].unique())

['high', 'medium', 'low']
Categories (3, object): ['low' < 'medium' < 'high']

In [20]:
# second dataset
import pandas as pd
import numpy as np
data = {
    'order_id':['01','02','03','04','05','06','07','08'],
    'order_value':[250,450,120,600,300,150,500,220],
    'delivery_time':[30,45,25,60,35,20,50,28],
    'distance_km':[5,8,3,10,6,2,9,4]
}
df = pd.DataFrame(data)
print(df)

  order_id  order_value  delivery_time  distance_km
0       01          250             30            5
1       02          450             45            8
2       03          120             25            3
3       04          600             60           10
4       05          300             35            6
5       06          150             20            2
6       07          500             50            9
7       08          220             28            4

In [22]:
#binning order value
bins = [0,200,400,700]
labels = ['low order','medium order','high order']

df['order_category'] = pd.cut(df['order_value'],bins=bins,labels=labels)
print(df)

  order_id  order_value  delivery_time  distance_km order_category
0       01          250             30            5   medium order
1       02          450             45            8     high order
2       03          120             25            3      low order
3       04          600             60           10     high order
4       05          300             35            6   medium order
5       06          150             20            2      low order
6       07          500             50            9     high order
7       08          220             28            4   medium order

In [23]:
# binning delivery time
bins2 = [0,30,45,70]
labels2 = ['fast','normal','slow']

df['delivery_speed'] = pd.cut(df['delivery_time'],bins=bins2,labels=labels2)
print(df)

  order_id  order_value  delivery_time  distance_km order_category  \
0       01          250             30            5   medium order
1       02          450             45            8     high order
2       03          120             25            3      low order
3       04          600             60           10     high order
4       05          300             35            6   medium order
5       06          150             20            2      low order
6       07          500             50            9     high order
7       08          220             28            4   medium order

  delivery_speed
0           fast
1         normal
2           fast
3           slow
4         normal
5           fast
6           slow
7           fast

In [25]:
bins3 = [0,4,8,10]
labels3 = ['short distance','medium distance','high distance']
df['distance_category'] = pd.cut(df['distance_km'],bins=bins3,labels=labels3)
print(df)

  order_id  order_value  delivery_time  distance_km order_category  \
0       01          250             30            5   medium order
1       02          450             45            8     high order
2       03          120             25            3      low order
3       04          600             60           10     high order
4       05          300             35            6   medium order
5       06          150             20            2      low order
6       07          500             50            9     high order
7       08          220             28            4   medium order

  delivery_speed distance_category
0           fast   medium distance
1         normal   medium distance
2           fast    short distance
3           slow     high distance
4         normal   medium distance
5           fast    short distance
6           slow     high distance
7           fast    short distance

In [24]:
# COUNT OF CATEGORIES
print(df['order_category'].value_counts())
df

order_category
medium order    3
high order      3
low order       2
Name: count, dtype: int64

,order_id,order_value,delivery_time,distance_km,order_category,delivery_speed
0,01,250,30,5,medium order,fast
1,02,450,45,8,high order,normal
2,03,120,25,3,low order,fast
3,04,600,60,10,high order,slow
4,05,300,35,6,medium order,normal
5,06,150,20,2,low order,fast
6,07,500,50,9,high order,slow
7,08,220,28,4,medium order,fast

In [26]:
# convert order_id to uppercase
df['order_category'] = df['order_category'].str.upper()
df

,order_id,order_value,delivery_time,distance_km,order_category,delivery_speed,distance_category
0,01,250,30,5,MEDIUM ORDER,fast,medium distance
1,02,450,45,8,HIGH ORDER,normal,medium distance
2,03,120,25,3,LOW ORDER,fast,short distance
3,04,600,60,10,HIGH ORDER,slow,high distance
4,05,300,35,6,MEDIUM ORDER,normal,medium distance
5,06,150,20,2,LOW ORDER,fast,short distance
6,07,500,50,9,HIGH ORDER,slow,high distance
7,08,220,28,4,MEDIUM ORDER,fast,short distance

In [27]:
# sort values
sorted_df = df.sort_values(by='order_value', inplace=True, ascending=False)
df

,order_id,order_value,delivery_time,distance_km,order_category,delivery_speed,distance_category
3,04,600,60,10,HIGH ORDER,slow,high distance
6,07,500,50,9,HIGH ORDER,slow,high distance
1,02,450,45,8,HIGH ORDER,normal,medium distance
4,05,300,35,6,MEDIUM ORDER,normal,medium distance
0,01,250,30,5,MEDIUM ORDER,fast,medium distance
7,08,220,28,4,MEDIUM ORDER,fast,short distance
5,06,150,20,2,LOW ORDER,fast,short distance
2,03,120,25,3,LOW ORDER,fast,short distance